### ISSUE TITLE
use spago for building purescript packages

### ISSUE THREAD

**Issue by cdepillabout** [purifix/purifix#3]
Right now the `purescript2nix` function directly calls `purs compile` on the input PureScript source files:

https://github.com/cdepillabout/purescript2nix/blob/8f434d88c0259608b1955db2f97d5fa458bd55e6/nix/build-support/purescript2nix/default.nix#L94

This works, but it would be nice to change this to instead build with `spago`.

There are a couple advantages to building with `spago`:

- Developers do most day-to-day development with `spago`, so building with `spago` in Nix will mirror that process better.  It is always annoying to have a bug that only occurs in CI, or a bug that only occurs when building with your day-to-day dev tools (but doesn't occur in the Nix build).
- Spago has built-in support for using alternative backends, so building with `spago` may make implementing #2 easier.
- Spago has built-in support for automatically using `psa`.

**Comment by cdepillabout** [comment]
In order to build with `spago` in Nix, I believe this issue will need to be fixed: https://github.com/purescript/spago/issues/575

**Comment by considerate** [comment]
I think that we should depend on `spago` until `spaghetto` is stable, and even then I'm not sure. The current `spago` doesn't yet work well with the registry.

**Comment by considerate** [comment]
I’m closing this because it seems like there are quite a few things like incremental compilation that would be much more difficult if we were to use spag(hett)o rather than calling the purescript compiler directly.

Feel free to reopen if there’s a good plan of incorporating spago or if there’s a use case that would be much easier to support by going through spago.
