### ISSUE TITLE
Monorepo Template Repo

### ISSUE THREAD

**Issue by thought2** [purifix/purifix#33]
First of all, I'm really happy to see this tool. Especially the monorepo/local packages support is what I am interested in. This was a missing piece in spago2nix and could only be solved by a hack of providing extra sources.

So I was trying to setup a repo that has all the boilerplate needed for a multi package, client/server monorepo. Current state is here: [purifix-monorepo-template](https://github.com/thought2/purifix-monorepo-template)

So far everything described in the README worked really well. However, I'm facing two problems:

1. IDE full rebuild command
In order to make the IDE trigger a full rebuild (former `spago build --purs-args --json-errors`), I wonder which command to use now. I can chose the `purifix` CLI that I get when entering a dev shell. But this seems to work only for a specific entry point local package. That means all the other local dependencies are already baked in as dependencies. Concretely, If I change something in a "common" local package, and I've used the purifix nix function pointing to a `server` local package. Then the purifix CLI does not relfect the change.
Concretely, I think what I'd need here is a CLI command, that builds/caches all externs dependencies with nix, and all the local dependencies as they are checked out.

2. Caching of unchanged local packages. If I stay with the example above. A package called "common" should not be rebuilt if the only change I am making is in the sources of a 'server' local package. Currently, to me it looks this is not the case. If you have many local packages and say a nix only CI pipeline, then making a trivial change in an entry point local package can cause all the local packages to be rebuilt. Compile times in larger PureScript projects can get quite long, and having this sort of caching would be really cool.

Well, I've just started to look into purifix, so maybe I am overseeing obvious things here?

**Comment by thomashoneyman** [comment]
@thought2 it looks like that repository link is private (I'm interested in this topic as well).

**Comment by considerate** [comment]
> I wonder which command to use now. I can chose the `purifix` CLI that I get when entering a dev shell. But this seems to work only for a specific entry point local package.

That's a good point. I suppose extending purifix with the concept of a meta-package that contains the sources of multiple actual packages could be a good idea. That way you could enter the shell and only precompile the dependencies of your top-level packages but not your packages themselves.

> Caching of unchanged local packages. If I stay with the example above. A package called "common" should not be rebuilt if the only change I am making is in the sources of a 'server' local package. Currently, to me it looks this is not the case. 

That's true. Currently all packages in a monorepo refer to the `src` which includes the hash of repo as a whole. This means that all packages need to be rebuilt if the `src` changes. I don't know immediately how to optimize this so that each package can be built independently while still allowing one package to depend on another package in the same repo.

**Comment by thought2** [comment]
> @thought2 it looks like that repository link is private (I'm interested in this topic as well).

oops. true, changed it to public

**Comment by considerate** [comment]
> IDE full rebuild command

> IDE trigger a full rebuild (former spago build --purs-args --json-errors)

The devshell `purifix` executable is a wrapper on `purs compile`. As such it doesn't support building "all" sources at the moment. What would such a command look like in your opinion? Should it compile all `$pkg/src/**/*.purs` files for each local package `$pkg`?

I think listing multiple local packages in the `develop` call is probably the smallest iteration that moves us towards a better CLI experience.

**Comment by considerate** [comment]
@thought2 @thomashoneyman Would you be available to discuss how to design the devShell to support monorepos better?

Specifically, I don't really know how to best find the location of the packages relative to the flake in a way that it feels intuitive.

If you are able to discuss this, what would be a good channel to use? A video call or a slack chat or something else?

**Comment by thomashoneyman** [comment]
Perhaps we could do a call in the https://purescript.org/chat? I’m traveling out of the country until next Thursday so wouldn’t be able to do it until then

**Comment by considerate** [comment]
@thomashoneyman That sounds like a good place for the call. I’ll try to gather my thoughts on the development shell until then.

I’ll probably be available next Friday night and the following weekend. I’m in the JST time zone (UTC+8) so probably a later time of day (in Japan) would be preferable.

**Comment by thought2** [comment]
Sure, I'd be up for a call, too. I'm in UTC+1

**Comment by considerate** [comment]
That makes the coordination slightly tricky :P I could maybe do a bit past midnight JST (10 AM east coast US and 4 PM in Europe). It’s a bit early on your end @thomashoneyman but I don’t know a good time where the three time zones would work otherwise.

If we were to do separate calls I could do around 10 AM JST (I think that would be 8 PM US east coast) and then later during the evening e.g. 11 PM which would correspond to 3 PM CET (UTC+1), @thought2. I think a single call would be nicer, though.

What do you think?
